import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/context/toast-context";
import { TanstackProvider } from "@/components/providers/tanstack-provider";
import { UserProvider } from "@/components/context/user-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fillo Copy",
  description: "Generated by haseeb ahmed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ToastProvider>
          <TanstackProvider>
            <UserProvider>{children}</UserProvider>
          </TanstackProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
